import pytest
import csv
import pandas as pd
import yaml
import random


def test_quiz_selection():
    # Reads the Quiz names from the csv file and shows each Quiz name.
    table_of_contents = "table_of_contents.csv"
    with open("table_of_contents.csv", "r") as csvfile:
        table_of_contents_reader = pd.read_csv(csvfile, usecols=["Quiz Content"])
        for row in table_of_contents_reader:
            print(row)
    assert type(row) == str

def test_tank_appearance_quiz_answers():
    # Reads the correct answers of the Tank Appearance Match Quiz from the csv file and store them in variables.
    # The Tank Role Match Quiz works under the same logic.
    tank_quiz_answers = "tank_quiz_answers.csv"
    with open(tank_quiz_answers, "r") as csvfile:
        tank_appearance_quiz_answers_reader = pd.read_csv(csvfile, usecols=["Pic ID", "Tank Name"])
    tank_appearance_quiz_answers_dictionary = tank_appearance_quiz_answers_reader.to_dict() # Modifies the dataframe to the dict type.
    assert tank_appearance_quiz_answers_dictionary["Pic ID"][0] == "ussr_kv_2" and tank_appearance_quiz_answers_dictionary["Tank Name"][0] == "KV-2"

def test_tank_role_match_quiz_answers():
    # Reads the correct answers of the Tank Role Match Quiz from the csv file and store them in variables.
    # Uses the same logic as Tank Appearance Match Quiz.
    tank_quiz_answers = "tank_quiz_answers.csv"
    with open(tank_quiz_answers, "r") as csvfile:
        tank_appearance_quiz_answers_reader = pd.read_csv(csvfile, usecols=["Tank Name", "Tank Class"])
    tank_appearance_quiz_answers_dictionary = tank_appearance_quiz_answers_reader.to_dict() # Modifies the dataframe to the dict type.
    assert tank_appearance_quiz_answers_dictionary["Tank Name"][0] == "KV-2" and tank_appearance_quiz_answers_dictionary["Tank Class"][0] == "HT"

def test_read_all_quiz_answers():
    # Reads all answer sets and store them in a dictionary.
    tank_quiz_answers = "tank_quiz_answers.csv"
    with open(tank_quiz_answers, "r") as csvfile:
        tank_appearance_quiz_answers_reader = pd.read_csv(csvfile).set_index("Pic ID") # Uses 'Pic ID' column as an index.
    all_tank_quiz_answers_dictionary = tank_appearance_quiz_answers_reader.to_dict(orient='index') # Modifies the dataframe to the dict type by each row, using the column name as each key.
    assert all_tank_quiz_answers_dictionary["ussr_kv_2"]["Tank Name"] == "KV-2"

@pytest.mark.parametrize("player_answer, expected_answer", [("KV-2", "KV-2"), ("Maus", "KV-2")])
def test_check_player_answer(player_answer, expected_answer):
    # Lets you know if your answer is correct.
    point_earned = 0
    answers_dictionary = {"ussr_kv_2": {"Tank Name": "KV-2", "Tank Class": "HT"}}
    expected_answer = answers_dictionary["ussr_kv_2"]["Tank Name"]
    message_correct = f"Yes! It's {expected_answer}!"
    message_wrong = f"No. It's {expected_answer}."
    if player_answer == expected_answer: # If your answer is correct, it increases the point_earned and shows message_correct.
        point_earned += 1
        print(message_correct)
        assert point_earned == 1
    else: # If your answer is wrong, it doesn't increase the point_earned and shows message_wrong.
        point_earned += 0
        assert point_earned == 0

def test_call_a_random_tank_pic_and_name():
    # Call a correct set of the Pic ID and tank name randomly.
    quiz_quiestions_dictionary = {
        "ussr_kv_2": {"Tank Name": "KV-2", "Tank Class": "HT"},
        "usa_sherman_easy_8": {"Tank Name": "Sherman Easy 8", "Tank Class": "MT"}
    } # Sample dictionary with tank Pic IDs and correct value sets. This part should be generated by reading the tank_quiz_answers.csv.
    random_target_key = random.choice(list(quiz_quiestions_dictionary.keys())) # Stores a randomly called key.
    random_quiz_question = quiz_quiestions_dictionary[random_target_key] # Accesses the value set associated to the randomly called key.
    assert quiz_quiestions_dictionary[random_target_key]["Tank Name"] == "KV-2" or quiz_quiestions_dictionary[random_target_key]["Tank Name"] == "Sherman Easy 8"
    assert quiz_quiestions_dictionary[random_target_key]["Tank Name"] != "Maus"

@pytest.mark.parametrize("question_sets", {"pic_1": {"Tank Name": "Pic 1 Tank", "Tank Class": "Pic 1 Class"}, "pic_2": {"Tank Name": "Pic 2 Tank", "Tank Class": "Pic 2 Class"}, "pic_3": {"Tank Name": "Pic 3 Tank", "Tank Class": "Pic 3 Class"}, "pic_4": {"Tank Name": "Pic 4 Tank", "Tank Class": "Pic 4 Class"}, "pic_5": {"Tank Name": "Pic 5 Tank", "Tank Class": "Pic 5 Class"}}) # Sample quiz question sets for test purpose.
def test_create_random_tank_appearance_quiz(question_sets):
    # Creates a random tank appearance quiz question.
    for question_key in question_sets:
        # Pops out a random key among the dictionary and stores it in a variable.
        random_question = random.choice(list(question_sets.keys()))
        # How can it tell if the question is not duplicated?

